name: build mobile

on:
  push:
    branches-ignore:
    - 'dependabot/**'
  pull_request:
  workflow_dispatch:
  
defaults:
  run:
    working-directory: ./cmd/aries-agent-mobile

jobs:
  build-ios:
    name: Build iOS bindings
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Gomobile
        run: |
            go install golang.org/x/mobile/cmd/gomobile@latest
            go install golang.org/x/mobile/cmd/gobind@latest
            go get golang.org/x/mobile/cmd/gobind
            go get golang.org/x/mobile/cmd/gomobile
            gomobile init
        env:
            GOPROXY: https://proxy.golang.org,direct
            GO111MODULE: "on"
      - name: build dependencies
        run: make dependencies
      - name: build iOS bindings
        run: make bindings-ios
      - name: Save iOS bindings
        uses: actions/upload-artifact@v3
        with:
          name: ios-bindings
          path: ./build/ios
  build-android:
    name: Build Android bindings
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Gomobile
        run: |
            go install golang.org/x/mobile/cmd/gomobile@latest
            go install golang.org/x/mobile/cmd/gobind@latest
            go get golang.org/x/mobile/cmd/gobind
            go get golang.org/x/mobile/cmd/gomobile
            gomobile init
        env:
            GOPROXY: https://proxy.golang.org,direct
            GO111MODULE: "on"
      - name: build dependencies
        run: make dependencies
      - name: build Android bindings
        run: make bindings-android
      - name: Save Android bindings
        uses: actions/upload-artifact@v3
        with:
          name: android-bindings
          path: ./build/android
  create-ios-release-asset:
    name: Create iOS Release Assets
    runs-on: ubuntu-latest
    needs:
      - build-ios
    steps:
      - name: Fetch iOS libraries
        uses: actions/download-artifact@v3
        with:
          name: ios-bindings
          path: ios/

      - uses: a7ul/tar-action@v1.1.2
        with:
          command: c
          files: ./ios
          outPath: 'aries-ios.tar.gz'

      - name: Add library artifacts to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: aries-ios.tar.gz
          asset_name: 'aries-ios.tar.gz'
  create-android-release-asset:
    name: Create Android Release Assets
    runs-on: ubuntu-latest
    needs:
      - build-android
    steps:
      - name: Fetch Android libraries
        uses: actions/download-artifact@v3
        with:
          name: android-bindings
          path: android/

      - uses: a7ul/tar-action@v1.1.2
        with:
          command: c
          files: ./android
          outPath: 'android-ios.tar.gz'

      - name: Add library artifacts to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: aries-android.tar.gz
          asset_name: 'aries-android.tar.gz'
        
        
